### ISSUE TITLE
What is the purpose of the Events object in the example cloudformation file? 

### ISSUE THREAD

**Issue by sinistersig** [vendia/serverless-express#149]
Hi,

Can someone explain what is the purpose of having the [Events object](https://github.com/awslabs/aws-serverless-express/blob/42a5501f2ef393461e6d53c4ab28ab343d83044b/example/cloudformation.yaml#L62) in  the cloudformation file? The reason why I ask is that I was able to comment it out, rebuild the stack and still be able to create a user (POST /users).

Thanks.

**Comment by brettstack** [comment]
Good catch. That template explicitly sets up the permission and role. However, the Event object does that for you. If you uncomment the Event object again, and comment on the permission and role resource, you should see that it still works AND the template is simpler. Let me know if that works. I'll verify on my end also and remove those resources if confirmed.

**Comment by sinistersig** [comment]
I tried removing the permissions and it failed.

**Comment by sinistersig** [comment]
I am wondering if the Events object is redundant whenever using the swagger file [docs](https://docs.aws.amazon.com/lambda/latest/dg/serverless_app.html).

**Comment by villasv** [comment]
> That template explicitly sets up the permission and role. - @brettstack 

Do you mean the workaround for https://github.com/awslabs/serverless-application-model/issues/59? We should be able to remove `LambdaApiGatewayExecutionPermission` after the fix, right? And then the `Events` object becomes useful again?

**Comment by brettstack** [comment]
Ahh, that's right. Once we merge that PR we should be able to remove those resources

**Comment by brettstack** [comment]
If someone wants to send a CR removing the permission and role, I'll merge it when it's ready. :)

**Comment by yuyokk** [comment]
@brettstack I've created a PR #185 for this. Please check whenever you have time.
Thanks
