### ISSUE TITLE
[Feature] Additional examples

### ISSUE THREAD

**Issue by brettstack** [vendia/serverless-express#18]
- Additional frameworks
 - GraphQL
 - Server-Side-Rendering

**Comment by happylinks** [comment]
Hi, I just started a project that has Server-Side-Rendering and uses aws-serverless-express. You can find it here: https://github.com/happylinks/blrplt

**Comment by brettstack** [comment]
Awesome! I'll use it as a reference for the example here.

**Comment by honey93** [comment]
I can do Vue.JS SSR integration with this ServerLess and can push, will that example be good?

**Comment by brettstack** [comment]
Indeed it would. First need a PR to `mv example examples/basic`
