### ISSUE TITLE
Binary files can't be opened by the browser

### ISSUE THREAD

**Issue by vikobg** [vendia/serverless-express#194]
Hello, 
I want to apologize in advance if it's not a bug in the library, but a lack of knowledge of my side. 

I'm using serverless-express framework with aws lambda and with proxy integration to API gateway. I have the following problem with binary files: This is what I return from my lambda endpoint:

```
 res.writeHead(200, {
      'Content-Type': imgType || 'image/jpg',
      'Content-Length': Buffer.byteLength(imgBuffer)
 });
 res.end(imgBuffer); 
```

I have also change the setting of my api gateway Binary Media Types to 'image/*'

The problem is that when calling it from postman for example with Accept header image/* everything is ok. Everything is ok and when I use it as follows

`<img src="urlToApiGataway"/>`
But when I open it in the browser the image doesn't render(doesn't show). I guess it's because of the Accept header that chrome is sending. This is the chrome header: accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,/;q=0.8

Do you have any idea how I can fix that and the image can be accessed directly from the browser ?

P.P. Changing Binary Media Types to
`*/*`
works, but then my OPTIONS method return 500 which is not ok, so I guess this is no the way to do it.
My lambda binary config:
```
const binaryMimeTypes = [
  'application/javascript',
  // 'application/json',
  'application/octet-stream',
  'application/xml',
  'font/eot',
  'font/opentype',
  'font/otf',
  'image/jpg',
  'image/jpeg',
  'image/png',
  'image/svg+xml',
  'image/*',
  'text/comma-separated-values',
  'text/css',
  'text/html',
  'text/javascript',
  'text/plain',
  'text/text',
  'text/xml'
];

const server = serverless.createServer(app, undefined, binaryMimeTypes);
export const handler = (event, context) =>
  serverless.proxy(server, event, context, 'PROMISE').promise;
```

Thank you in advance.

P.P. the response headers is chrome are:
access-control-allow-origin: *
content-length: 77772
content-type: image/jpeg
date: Sat, 10 Nov 2018 17:12:58 GMT
status: 200
via: 1.1 1764af62d635a1a6ee51aabc37405452.cloudfront.net (CloudFront)
x-amz-apigw-id: QJ-wMHaJjoEFwgw=
x-amz-cf-id: KTB1IRJRoMPIOCIZW2KWDIcIUA7dmnRvoAQl1ltPHKuwHUD9rRobsg==
x-amzn-remapped-connection: close
x-amzn-remapped-content-length: 58328
x-amzn-remapped-date: Sat, 10 Nov 2018 17:12:58 GMT
x-amzn-requestid: df482bc1-e50b-11e8-9473-07723a141d77
x-amzn-trace-id: Root=1-5be7119a-59d520c44105f3d0f0acb9a8;Sampled=1
x-cache: Miss from cloudfront
x-powered-by: Express

I don't see isBase64Encoded property here, shouldn't it be part of them ?

**Comment by duro** [comment]
@vikobg I actually figured out a way around the 500 error on the OPTIONS methods (assuming you are using the Mock based CORS setup). If you open up the Integration Response > Click into the 200 response > then go to Mapping Templates

Remove `application/json` and add `image/jpeg` with a blank template, it works!

I got to this place after a long series of chats with AWS support. Not sure if this is going to be the exact solve in all cases, but it has us now able to support binary and non-binary response, with `*/*` as our Binary Media Types, and OPTIONS works just fine.

Why?

I have no fucking clue.

My challenge is that now I have to figure out how to end up with this configuration when using Serverless and CloudFormation which is not straight forward.

Just be aware, this has NOTHING to do with `aws-serverless-express`

**Comment by brettstack** [comment]
Update the Swagger file should do the trick

**Comment by duro** [comment]
@brettstack that is QUITE the pain, especially if you are using serverless framework and CloudFormation. The solution we came up with with AWS support has proven to be quite solid, and I have made the solution into a plugin here:

https://github.com/duro/serverless-binary-cors

**Comment by prasanthsd** [comment]
@duro Does your solution still work? I just tried manually in API gateway and it still returns 500 after adding image/jpeg with an empty template to the mapping templates.

**Comment by ciryon** [comment]
I had similar problems when attempting to send a zip file, but eventually instead decided to redirect to a presigned (short lived) S3 url. In case it helps anyone else.
