### ISSUE TITLE
[Request] Add support for multi-value parameters

### ISSUE THREAD

**Issue by brikis98** [vendia/serverless-express#196]
It looks like last month, [API Gateway added support for multi-value params](https://aws.amazon.com/about-aws/whats-new/2018/10/amazon-api-gateway-adds-support-for-multi-parameters/), so you can have the same header and query string params repeated multiple times with different values. 

It looks like these are part of [new fields on the event object](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format) called `multiValueHeaders` and `multiValueQueryStringParameters`. 

Would it be possible to use these when translating the event object to a request object rather than the original, single-valued versions?

**Comment by brettstack** [comment]
I have this working in a local branch as part of a larger release.

**Comment by rnowosielski** [comment]
@brettstack do you maybe have an idea when this might get released?

**Comment by makstaks** [comment]
@brettstack is this project still actively being worked on? There's a number of PRs waiting and it's unclear when the next release is coming.  I'm trying to decide if I should just wait or possibly fork this project (I want to avoid forking).

**Comment by erodrig** [comment]
amplify uses this by default, if the project will have no maintenance from aws, they shouldn't push it . I got surprise when I saw no support for query string parameters

**Comment by albertossilva** [comment]
I have opened the PR https://github.com/awslabs/aws-serverless-express/pull/232 with this change, now I am using my fork while the PR is not merged or the branch from @brettstack get merged and published.

**Comment by Hyperblaster** [comment]
Is this project still maintained?

**Comment by brettstack** [comment]
I left AWS last year and no one has picked it up. I'll reach out to some old colleagues and see if we can organize something so that I can continue providing support.

**Comment by Hyperblaster** [comment]
@brettstack No worries, thanks for the quick reply. I might be interested in maintaining but will need to check my capacity

**Comment by brett-vendia** [comment]
Now maintaining this project under http://vendia.net/ 👍 v4 coming soon
