### ISSUE TITLE
windows config + git bash yields bad lambda name

### ISSUE THREAD

**Issue by Vandivier** [vendia/serverless-express#208]
Using git bash on Windows 7, within /basic-starter, I ran:
`npm run config -- --account-id="XXX" --bucket-name="XXX" [--region="XXX" --function-name="YYY"]`

This resulted in cloudformation.yaml with illegal lambda function name `YYY]`, including the right bracket.

Everything worked once I went in and manually deleted the right brackets. If the README meant to indicate optional params by using brackets, a simple documentation update to clear that up will be nice. Otherwise it might be an interpolation issue, and I'm not sure whether it's specific to my use case or not. You might also just add documentation saying "if it fails check whether your lambda was named this way" and delete the extraneous bracket.

**Comment by brett-vendia** [comment]
Fixed in v4
