### ISSUE TITLE
Issue with route middleware returning function, request timeout

### ISSUE THREAD

**Issue by si-harps** [vendia/serverless-express#218]
Hi, in the following scenario the request times out (10.01s - user defined timeout). 

The route is matched as expected with the request being passed to the ```permission``` function of the ```has``` library to check the certain attributes of the requestee's session object.

The ```permission``` function returns a function on app load which accepts ```(req, res, next)``` as it's 3 parameters. However, this function is never called causing the request to timeout at 10s as defined in my configuration yml file.

Any ideas?

```
// analytics.routes.js

const express = require('serverless-express/express');
const router = express.Router();

const controller = require('./controllers');
const { has } = require('./lib');

router.get('/analytics/conversion-views', has.permission('canViewAnalyticsDashboard'), controller.conversionViews);
```

```
// lib/has.js

function permission(permission) {

        // Able to log permission argument 

	return function(req, res, next) {

                // Never gets called!

		if (!req.session)
			return res.sendStatus(401)

		const session = req.session.get({ plain: true })
		const roles = extractRoles(session);
		const permissions = extractPermissions(session);

		if (!match(permission, roles, permissions)) 
			return res.sendStatus(401)

		return next()
	}
}

module.exports = { permission }
```

**Comment by simonguldstrand** [comment]
I also have problems with things not getting executed. Not resolving promises etc. See my issue, created just before yours.
