### ISSUE TITLE
Can't make it to work with aws-sam

### ISSUE THREAD

**Issue by therepo90** [vendia/serverless-express#236]
I'm using the basic-starter example with aws-sam but it does not work - the lambda gets timed out as the request doesn't go to my express app server.  The whole lambda handler gets hit by request but hangs as if the server never started( no console logs whatsoever). Versions: latest.

```const express = require('express');
const expressApp = express();
const port = 3000;
expressApp.get('/', (req, res) => {
    console.log('helo world');
    return res.send('Hello World!');
});

expressApp.listen(port, () => console.log(`Example app listening on port ${port}!`));

exports.expressApp = expressApp;

```

template.yaml:

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs8.10
      CodeUri: lambda/
      Description: ''
      MemorySize: 128
      Timeout: 40
      Events:
        lambda:
          Type: Api
          Properties:
            Path: /
            Method: 

is it possible to use this package without other yamls for proxies only using aws-update-function ?

**Comment by brettstack** [comment]
Try using Node 6. Also, what's your handler look like?

**Comment by therepo90** [comment]
```
// lambda.js
'use strict'
const awsServerlessExpress = require('aws-serverless-express')
const app = require('./app')
const server = awsServerlessExpress.createServer(app)

exports.handler = (event, context) => { awsServerlessExpress.proxy(server, event, context) }
```
