### ISSUE TITLE
Response with large JSON values not getting, for less values it is working fine.

### ISSUE THREAD

**Issue by sreekarsai08** [vendia/serverless-express#245]

**Comment by bidva** [comment]
having similar Issue here working with simple JSON but as soon as I make it heavier showing me strange error like this 
`{ statusCode: 200,
  body: '\u001f�\b\u0000\u0000\u0000\u0000\u0000\u0000\u0003�}�O[ɶ�\u0012��ӽ�.��\u0007KW�!!��!\u0004\b�<=�j�\u0006��m�\u001c�����6;�`����ᜎ\bJl3��Wk��Z�\\\tv`W���+�c�g\u001fc���1�4W�=�Ǖ�W�\u0003;���\u0003�/\u000f6?��#���;���\u001fs���Ux��M�ٱ����H�{\u001ew.;.��߈ĜI̴d��\u000f����\u001f��\u0017q3�<x��������m���\u000e��םw\u0007�۽����bmk�廭����W�\u0017���v��;����\u001f�Ѐ/L�^�3�%�g�����5{~���w\u0019_��A��x�)~_ɿO�e�sq\u0016\u0007�\u0005\u0012\u001e�\u000e���E<\u001f�4\t՜���W;��"h�]��&&�\u0014X� \u0013��\'\u0014\'\u0018�T�1\u0014\u0005K��d�\u0013ڣ�\f�Ny�d������J\u0013��%\u0011_��-~�\n�� �\u0010�\u0007D5��\u0006��3|A!)x���o�^~�\u001f�����v�y{q�8t� \r\n\u000f�x��q۞��߷��%����n����;��(v]>���n�C��\u000e�\u001e\u001c~k�W���w�f�ݱ_,��\u001a�5#3P���n׹����CM}\u0018\u0014��L\u001c�q\u001c0j\u001eG�2�\u0015(Pw(0QH��F$y�8\u0017\u001a9�5�Z9E�\'<�j\u0014�\u0003b��6�i0N��|x��\u0011�&\u0011\u0000Ϟ�\u0007�o\u0017G�/�@nc\u0010hw�\u000f�O(\u0000�\u0016\u00006w\u001e�@\r�ϒ��wW�B��U�\u0000y�����ƏK;�h\ni�;i��<�{��I\nq�\u0004\u0002@0�-�AX�\u001cwu�MY\u0013�&5\rJ�}i�\u0018{�����/F���\u0004��\u001dn��\u001cW\u001ek<����Z�n<��p���R!�I( `� �\u0005\u000e�\b��6\u0006qE\u0018҉\u0004�\u0003\u0003\u0011���ք\u0000%M�\u001aB�]���(�8���=\u0006\u00005\u000f\u0000n\u0016y�\u001f�\u0010:��ū��o\r\u0006\u0017��?�1|\u001b��q��q\u001e\u0007�X�z��U�^��/\u0011�k�КZ���+��\u0015�̫W�����{�?`��O+�\n"���\u0001�\u000f��!��[�}�3\u0015D�\u001d�\u0003i\u001f Ӛ�&�0�\u0001\u000e4��BI�\u001eq,�8�4�B>\u000e1�L, f� �8|Sc\u0012�\u0006S�MpH3ɑ�6$ɜ�LUC�\u0017���\u0010#��y\u0016�C�\u0017\'�Q��A����3���\u001fj�`\t{��a]\u001fn/�PkD��WZ�e�I���\u0014\u0012kJ�q��V�˚p#\u001a�Q<\u001bn�q���\u0015=�\u0006��˳��`\u001b�\u0006���\u001f�\u0010i\u0005���.�\u001b�8�\u0012ì@��C�%��\u0014,�,�\u0000���54a�L��E���u�&�\u00187�����/e6ݢɹ�VӚ�\'v_�0�\u0004\u0011�0!^��ݯ�\u000e_�İ\u0014;\u0016��\u000f6�B�c\u0011c�)80R�\u0003� |�\u001c�O��XJ\u001a\u0012��Do�X51\u0007�Ռ9��ٹ�\u0007�?��$e�7:O\u0010S��|���b{���z"-\u0013\t\u0006PP !|\u000bd=!NA ˢF�\u000b07�\u0010��њ[\u0012����\u0004J��B\u0014�`zL\t\f\u001e\u001c�tX�IX�\u001d?\u0004��1j����\te�����^<~�_\u0017\u0005J\u0011��L\u0014|��{���V\u0007\u001f���l�#�,\u001dG�\u0011���\b\u000b�[]`!�\u0006!q�9�HH0\u000390\u0007�\u0016�����\u0018�禆A\u0010\u0007D7�hR�P����1�h�7��t�c�\b�nxS� LE�\\$\b�/�o��=~߻��t ��@�a�q\u0014�\u0015#\u0005\n�\u001d\n\f�Qɨ\u0010<�\u0011�^#ccD�;ɼ���\u001aa�\u0010\u0005\u0010�ʆ`�\u0001\n�#`�\u001e�c\u0000ض�ݓ�ع�]\u001aN~#sX\u0005!�L(\u001c\\�}���=Z��\u0016`\u0015\u001e��\u0019��0d\n\f\u0018qEn�pr���C�{�\u001c�\u001eqb!ԍ\t�C0$h\bX��\u0005\u0003���4\u00198�x,��L��\u001cf\u0001�z�\'�����\u0017�a�W�\u0019�\u001f�uN c\u001e�\n\u0019�[-��\u0017�\u0013���i�1��f��ǡ!E(� E�v�!<w�S�R\b\u0011q���T,!b���E�hu-h��!�nH=\u000b\u001a�x\f�\b4r^�\u0004>.�\u001c�\u0004�89\u000b\u0014��kN��A�{Þ�r�\tO�+<Y\u0015�#�!\\�@0z\u0007\fg��T\u0007\u0014���;\u0001��\u0004g�xg�H.)���!�\u001bd<���N����D�;���g�\u0001&�\u0013/��K����3{[\u0013\u0014�Gb�=Ks����\u0000_�̪�������:߾\\\u0010&�\u000f.Fx��\u0017\u0019s���@A�p*\u001d@!Rģ\u0004�2J����a\u001d��5�2\u001e�7�\u001b\u0000��x� 3�H\u0016\u0014h��d�p�\u0001pP$��\u0018\u0015e���L���6�������I#�\u0011\b4QC���@��&\\K��P:+\u0005�\f3\u001aEK��$iojX�\u0002\u0004�C5(�\u0013 (\u000es\u000e+Ѻ�ױ�\u0000\u0006�s�ΰyz󐕀[��\u000f�{�\'�����۶?U�#�s\u000f\u0000ks�\f\u0013A\u0005\u0013\u000f��\u0011\b���\u0000��\u0003\u0001��2\u001a\u0013�؂7�r�IQ�r��E����YmJ���\u0000\u000e\u001a�X&+�nzP���\u0003\u000bO8M��<v���\bh��>Fqv@7��j�\u000f9�l�a�r��YpEI��d\t���\f[�L29�\bH��G!x��\b��TK���A\u0003�\u0006\u0019\u000f%ڃ~\'�6\u0004\u000f���n��\u0011\u0004\\�o��\u000b��ST��4�!;�ٗ�n�\u000e��\u0017��\u001fR:v\u0001�.\u0012\b\u0013%\u0007��z\u001c\bQ��Ò/a9f$µ\'B\tč�H+\rN\u0001�\u000e�M\u000b��T\u0003��\u0003#M.\u001a��\u0007\u0015�9@0K\u000b��;\u00035�H6�N�L��\u0004�ka�����������,\u0013�r�[��,�L�dSxx�\u000b��R\u000e��q�l\n�\b�\u0004<E�9�.Ad,h��M�\u001bD�\u0019A$��=��\u001bn�~B�ػ�Ea�n�(�l(\u001c�ۦ_�z}���>a�8�\u001aH��\u0004\u001eҨ�\u001d}Q�`%�B�()�\u0018%C#�b���@,\u0011�<\b\u0017��j<��o"��TC\n<�\u0010� -��\u001c���\u0014�s���������K�>�[;�l?�z���|Ȭ\u001b�!z]ԦYɂP�x�x��\u001a���`$,Ș(��ߧ*\u0014��:h���Y�`9\u0015\r\u001c�A�ZjMj�Z�9�P�r<<Z��x��q|y���i�0���0n�\u0014s\u0007\u0007\u001c\u000b�-+�\n�:l���k\u0003�"���c$E�цd�\u0010:�p`��rbI*<�X��d,��\u0018k�wZ\u001f\u0012U��V;v\u000f\u000en..��=N��\bۓ!�\u0012���\u0011��gCo�$<x�lT�!\u001a\fğƘ\\�4H�g�1�ēj\u0000�\u001c�\u0010\u0001?�a�xH�+���r��Vwv�_�|\u001f�\u00121�[�ם���\r�j�OG̼9+\u000f�ɰ�a�����\b\'<(\u0015\u001c\u000bb\'�\u0005�RG�G�\'\u0011��R�*V�FXf�P���x"��\u0010\u001b�\b��"����y�\u000e���{>HQ��\u0002)%g"x���\u0001��3)\u001c0c�\u0017��\u0004Q\f�$�0�\u000e)\fg΄&c!m+��I8��eq2�uhԽ2O��\u001a4W�󓽯�7\'��W0H��#�<\u000e����+V�,��_0�-�`\u001aq\t\u000e�5� ´P�Jl��\u000b\u001bP0�a8��?4���\u000b��ؙ��^����a��ϻ\u0017G��G�`�\n��K^�7B\u0011o"\nAa�=�\u0010#ɈTd2\u001a�t�U�L�\u001c��8˝gL�iș�\u0015��B�\u001cy�J䜥#�<{����� �I_���7چ\r�\u0007\u0016\u001119�j�C&��(땔�1�\u0018=C�&�M�\u001b\\�iș�n�ő#\u0016��������ɩ���\f�CFջ�d������I1i�\\�4<��\n\u0003\u0015$M\f$\u0019iMe޾D\u000eo����j�fd�~A�,\u0012,�;�����KL���"w��*�a�$}XI\t\r. �Rn+\t\u0010jkO� JK*R��\u0012,\u0012��\u0006\u0011c�}x����?\u0015\'\u001d}����?�ez>8\u0001��\u0002\'%/$bǘ\u0017\u0004��,��"�\u000blu�v��\u0006���\u0011c�\u0003���\t��NS*3\u0012z� X���:�Y{ymo������g�\u001c:�\u0006k�\u000b�d� =�cDqL�\u001cGsw$F�pMS���\u001a��\u00109,�HJ6m��o�E��Բ\u001d7��\u0005�4\u000b3V�l\u001f�n^F{>P+�!\u0018�H\b�\u000f\u001d��Y��\u00035�\u0013���K��AN\u0019�\u0018\u0016F�d\u001d�U��\u0002\t�hXt�H�H\u001f[�;XH��\u001f�\u0011�4�9�e�Й]Զ\u001b.:k������\ti��DO�0\u000e.�$\u0010���-G�&P\u0002�xd �A\\\u0013�0\u0015`]���@�&�\u0007�i\nҐ�\\�s�0�?�$��\u0004���j\u000f�����$��/J\u001c�\u000e�<��Y\u0004��7�#�j��\b�\t�8\u0006\u0004��@�!�&\t�\u0013E�\u0012��X1r��\u000b�b�F\u0005�|\u0015���@���)\f\u0018�1\u0017�W��tZ�RYeO1}�ݞ}�⟾�\\~|���\u001b��-s\u0005����\u0010\u000fx��$$$\u0003Y3��%I!xM\u0014XYB*�Nt1z�4\tmb�`bL��\u0018"��I!�\u001f8����i�+(�1f�\u0015t��W�0��qk��\u0017�QF�~�\t��G����ˑQF ���Rk��ա�H&�KE�\u001bF�0A(�"��F\u00139ǿ\u0011:G"����n/��{\u001fB��ln���I8�\u0013X`C,PE����h�pN>#\u0007.\u0005�>2d,�H\u0002�E D���H%\u0016D�������ã�\u0015Y;O��o\u000ĕ��Iۛ����GR\u000f:\u0015�\n^�*\f���h t�\u001aqpҐ�TN,D��\u0005\u0019u]\r@Y��V�i�V�G��\u000fJ�+9p���Z\u0004;�%�D\u0018�QJ�\u0002�1�@ \u0004��"nCD��!eLHou$�F�m$\u0001�\u0014t�S����0���/���}5�G������\u0005H�\u0006�HJ��P��\u0005ѝ��\u0000\u00190�\u001e\'����8\bN��Hq\u001b}�:ZQ�\u000e��@\u0019�\u0006�t"8�b�I<:�O��\u0010P�k\u0006\u0010\f\u0006o۬��ƭ�4�h�U�J\f��m�BvLi̳����#m�Cr\fB\u0016�������d��\u00068�3xg�j���5Ok���5���r_W��.��n���h9~�\b\u0005�\u000f[ EY���S��EDF�K"��Y\u0002�r�\u0005VQMR\u0015��\u001e\n�nH��[ ��:�<��G�YM�\u001e��}\u001dN��ueK/�0�\u0011��Ţ\u000e&�r{\f$�h"�4�<\u00060\u0004.OT��⨰\u0011FW\'�F�BiS�\u0006�c\u000eq\u001b\u000e�щ�׽��\u0011^v���|}�UMN�\u001d͛7\u001b�{���M�l�17`b�\u0012�t\n\u0004�#�\f\u0015�n�ip��9��\u001ds���Xd��Dh��Yu�"\u000f��M��DO�,��n3Ҕs\r��I\u001do�׵gjՐ���;����w�f��O��`�˟��\u0014Q�\'8��@Z\u0004��_�\'4\n\n|F\u000fqS�A#\u001e\u000eWc8��x뻽������DO��Zս�5g_LK�,���ӣS9���\u0005f�\tG�<�����\u0018I^�"*\u0013eq�:��f\u001c��->�Չ\u0002\u0003>iJU\u0012�ֻ� ���\u001bB�ɨ�\u000f\u0010�/g�g\u000fo����=r5����[\u0010�\u001e\r~\u001a\b� |\n\b(/ң��SC\fH��\u00169����7�,\u0003k�(�4h����N\u0012]��x�\u001bp��\fX���?�\u0011���})\u000eޝx����섊��1�x��R`(�[�\f�0.�&�ګ\u001f�5\u0010\u001a�K\u0003\\���\r\u0016���ֽ��ڙ;��W���\u0012oS^�����W\u0015W�\u001ap�\u0018��!/�O�^��r<����E�E�U�UVxT�� |\u0011!d�pD.��\\(�2\n_C�};sP\u001e���9��\u0018�,�jg��b�\u0003��c�\r�Ȱ���\n{�-1��q{�������<O�(μ�f��\u0019\u000f�"�M\u001e��92\u000e�6\u001c\u0014\\\u0000g\u0012�ys��\u001e���}���\u0015�#QV\rcb\\z\u0011�L��w\f\u0007�|�0YD�\u0013\u001c����s�Μ7��\u001b�cg�O�8�f���1a�\u001858�P�\u001c�.��e�Ƣ�4י����g�8\u001b��e�N�g\u0018c�\u0010���\u000e9�\u0005"DHC��ATWǿ��h0�\u001e��b�|�^�\u0005!��d\u001c\u0013§ei���x<LȔu9.ฉ���A�\u0010��@��.%43��@i-u��H@Xn\u001aj�.7:�9\u0006��&\r��B\u001a^�g/l��\u0005CT|����f\u0014[�w�\u000bdq���8�����lw�f"�)&x���\u001f�Q��C�e����(\bff\u00167�ÎOvҟ����T���+o�cm�\u000f�aE\u001fG\u0001!C��,ko�cK(S��@\u0010�\u0012\u0002�\u0014<�\u0012�\u0019�/M�\\�U�@�q���\t��=�\u000bZ�t�[���u�/O֊��뷏�\u0019\u0001���{Y\u0016�\u0018��k�\u0006"b�g\u001d��J؀@)P\'�\u00063]+�̈́%\\̂QjZ��zf�#���"V\u0015}!�,�\u0019\nR\u0004W\u0016�_���\u000e\u0019�\u0002\u0012əhu��U\r�.EL�T4���0{��"\u0018Q��۝gsbE5<�_ۉ��W_�n��\u0016 ��\u0017�N����k�d}Y\u0016ð5�\u0004�P\u0002O\u000bd�\u0019Xb\u0003z99+\u0018�j�V\u0017�(�][ \u0013�\u001a��)�~>�9\u001c��s��+�a����S���_�6���U\u001a��\\Gy�\'w\u0018�˲\u001a�Bp&\u0010�\u0012��`��:�\u00046�E���;\u0002jD?�=��)��^��\u001a6�\u0010:���?��>�==��(`0��<���\u0012~�m�=�>2{7���)|,xA��e\u0015�`���M"\u0015\\^\n\u0001A��)OH��W�D����d��\u000f��j�Lb���#>\u001bٿ����Ԕ������:Z}���=��.>#C�,�Y���Kb�\u0016���k��\u0011\u001486��L�+{^��l�A�8��>�\\�r������\\��=I�䯔�\u0002���R��W��|^J���˔?5~臕�:\tA�K<"�\u0014���g}kA�-�FCX洫�A��B\u0018�����X�����vl��P\u001b��90�\u000b~\u0010��_�����ŉ��ڿX�\n��W��\fݽ�j\u0018��ZQ���Eof@Zj�4%\u0014�~\b�\u0006�u(�ܢK\u001bj|�Cx�s8|K\u0016�\u001cj�\u0016�������\u001b�Ϗ���P_�����yA��^\u001aaRn\u0016��.�g\u0002�`#2^\t\u0017 �ƕ���d\u000f\u0011v�I��\u0011��\u000b��j\u001a�\u001c뫣�\u001ckl�\'y3�ɹj\u0016\rJ��`������ҫF����g����敾z�4���\f\u001c�|\u001cN\t��L\'�¬��\u000b\u001d�\u0000\r^��\u000ei�8r�B&�(��F�J\u0015�cp�\u001f��Ԅ͌]�\u000f�I�\n\t��ݺ�Di0�3#����u�kzO�o�S7F<y\u0017�\b\u0006T\u000e��˲VL8���\u001aDC�ke�\u0011�#���29\u001ajt�S���X5�jh*Ƶ�\u001f\'?L�����\u0007f��O�W�Z7W�\r�?Y�Sy�\u000b�\u0017�\u0007�"u���\u000f�\u0006�v�G��y���\u0004=�\r\u0010)�Q\u001f^\u0019\f@H�\u0006�K�\u0006]2��r�\u001a`�p�n��\u000b7\u001b��s\f���\u0012���.��J䋘�Pc*�4��ȋ��6v�x����\u0010\u000b\u00109O\u000e9�E^\u0015�qd��T�VcF��\u0018(��q>p�ǹ��ǵ�OJ\u0015�q�1\u0015��u�ݍ��͝\u0016���XA_J\u001d�]�ЖeQ\u001e3\u0014I�=H�A���o��j�dt���]���\u0017Ew��cI��R}�Wl\u000b}�_��k\n�\u0007T���Vm�\u0013-\b�œo����I���\u001f��\u0016�\u0005,��P�xr��\u001e�zP܅��:=3\u0006$�A�1\'�\u0012Wp�\u0003E�\u0010���\\��z\u001c���\u000b�9�xܽ˓]��SD�3�,�O�\tX�!�:Pr��������in|��\u001f�<�T�yUV坤�I\u0003B�\u0004\u000e�\u0015/�b���B�J�%|�b��� �!��\u0014�b\u001b�mu���A�̅��k�w�c�2w�fs\u001cWL2!g��\u000e{�y�����X�͟_�0��+�9���sk$64!\u0013�\u001aΣ�Q%Ăp"��ک*��_Lp\u0013�o��3D��N�\u0014�T\u0000�v��̂e��\u0002~�9����G�}MK\u0016\u0018&\u0018��"�|\u0004\u001dj$2�\u00068P�%��Є^T����ޜ��}z���}�\u0000���草�a4c}R���\t�a\b���/e^%\u0007n�\r\u000e�\u0018��0\u0016#��E\u0010GXQ\u0019(��|���b�4�:���\u001d��\u0011�WH\u0018lu{��ۓ��FC\fi�,<\\��ˍ�ϴ���뇟\\͌Р�)�HU�\u000e\u001cw\u0012K�\u0015�h\fh ,O��\b�Ȓd���mZ&/�\'2w�Q��j,mp�\u000f�ޞL775�PO�d�Y\u001bP\u001fw��-Ip�}"Hy�\u0010����X\u000f>U0V{�\tVu�B�$jf��\u0005�08�Y��\u001b���D"#�\u0010<�O�J���F{\u001b9��pę\u0005��9��\u0012T\u000bf��U\u0014�!T� �\\�\u0004\u000b6n��=�9��S�\u0014#-�\u001fN_�����E��^�h�3������"���c�^�5�0u\u000e��R4ڧ"{�J�C��`\u0003!�\u000f\u001e��<���H�2�G\u0010�ƕ��J�\\�FNGO\u0010\t~\\"�\u0006�͌1���8?A�,\u0012\u0010�������:�7�T%�p�\u0002\f%�!�@�e\u0014E�5�ڃ7"mB�h��K$V�,�`��\u0007�Aƃ�q0h\b� N�H��[4�D\u0010h;Ĕr���\t����Y��q�\u0005Gks}\u001cQ�\'�\u001am��:�\u001b��cН��ޕ[\u0007g�|�z��7>.\u0013g�\f\u0007���a\u0011��B�ɲ4��%�\u001b�1C\u0010G;�g��Rk�3�\u001b�(��t�\u001c��\u0015΂R9%�\u001197Ir\u000b.v\u0001\u0011�\t3�\u0004�Ջ��ɻ�\u001f��/���r�/�r��0aS�9�s*�\t���s�\u0014�$\u001e�rO�\u0014I�DhUj�ę�\u0014N1���t�c68{���\u001e�l���9\u0016$V-q���\u001bӳ���;�O��\u0018�θ$��(���\u000eU2C�\u0016%\u0016@wD���8I��\u0016>��k�\u0016V�*&�\u001d�\bmR�Px�\f��\\�\u0003�A��\u0000��7����kqt�I���r\\�\u0011\u0006\b���@I� TʄuD� \u0005J.�c&!\u001c9&�{�qUa��\u0000+\u0016D\u0011�8\u0006�mѨc\u00110�<x\u001f�(�(\u001cނK�#\u0011��&DM�\u0018qa\u0016��!��o\u001d^�,�B��bT�\u0014�\u001cU�1\f\r�\u0010�\u0003�\u0011�p�\u0011�p"�\u0017�Ă#\u0000����[�Q�\u0011WL��\u0016�α?k��f{�z��R�R���\r�\u001b���������,\u00008Փ�\u001e�\u0002��#R\u001c��Jj\u0007�L�<\u0013���_�X���\u0005��s\u001cG�5*۳�S4�6��hL���٠aZ�H�bu\u0001��ҼȀ�\u0000��}��V�\u000f��0O�<��/�((���~H�$Ì ϴσ�#2\n�\u0004ǽ��iNx]mBy\u0013+�c�C��$�V\'*���\u0006Q�gvh��*/?�\\E��Tk��kX\u001d�;����\u0003�zsu���hq�*�"�p*5�(�Ѻ��\u0012�P΁AP6���w8���Au�;\u000f�s\u001f�3�3?�f��3(n��\\k\u0011�W�\u001b)8�a\u0006���(Ћ�3���\u0002���\u0010�j�T\u0002N>)!q���;�p����\u0015ӑ��pʸd�"\u0003~\u0010�y��J�g��\u001f�H\u0010�%�\bADI�\u001a<o�v��c"�\u001a\u001dD�"u4����ヮ�@/�\u001a�0?ln�%�%�\u0010��UEA\u0003\u001c�\u0007\u001da\u0001l\u0014�\u001e�\u001d\u0001d�+\u001a\u0001�h��\u0006����s��\u001cg\u000b.\u001a�w\u001f�9�?�w\u000e�Gjw#�$U�M�%\t�j\f:K��\u0004*fy���\u00005"�rZ*�\\�`�˂\b�gDQF8\u0012\u0003c.ϥ\r3J\u0002��;\u0014 ��:RD���GAsO�D�RJ�H$��{��@��`�~�9�h�E�R�\r�\u0014m�O��\u0006]\bL|d\u0018�`��\u0012�<�V��$����\u0001��<�!|\u0004��6\u0004�\u0001�:��̕�8�@�\u001a��\u000e�\tж��A��D�\u0014B넣[$�\u001cy�s�����얉3\r\u0018*pV�h\fe`_�\u0004G8e5�)U\u0004�%9\u0005�Ãв^xf��e�\'óӹ����l�F.�\u0015��\u0007�?��[���J\u0015�[���H\u000f��")7�Ap��BV$��\u0003{�\u0014�H���2E�R5����3�\u0000��K�~N1�"\u0001q\u001e>^\u0011����j���E%Q�4\u0019Ol�6o�09�6`N��\u0004�u��\u0014y�zq�)\u0016E��\u0018\u001f�:A��V2�)�6@��A����H���\u001e����*�\u001a�I\u0013l޾\tGŝJ�)& :��E����\u001b@P\u0013gݛ�Kur����e⌹a�I�\f\u001cf�����;�-\u0006R�Ax���$�\u0011�`C\r\u0016�\u0010g*3#���)�s��V8#�x��\u001b:my�P��\u001a\u000b�X�\u0012\u0007Ź-F�.\fg7[���_~�\u0010o��3?ZI�d�6��f�P�\u0017\u0015\u0012�%H�)p�B�*Ɣ`���\u0011�iR��T%����\u001c�3�Yv��~�5y��zt��ny�\u0001$N�v\t}\u001f7\f9X��4\u0002\u0013���f#�\u0004\u001f�%D �G�\u0010��\u0002��8\u000bD3�9��g�Q���\fOI�\u0004���������4�\u0006\f�G�\u0014��K\u0001�`=��6\u001dWJ�H�"YZ�\u000f�bm�x��X���7z�[��\u001a���!A!�\tɾU@��A��]JXa[�6��\u000f��$�g�:��K����J\'\u000e�J��c}\u000f\u0000�������\u0002\f_2�%�\u0000\u0000',
  headers:
   { 'x-powered-by': 'Express',
     vary: 'Origin, Accept-Encoding',
     'access-control-allow-credentials': 'true',
     'content-type': 'application/json; charset=utf-8',
     etag: 'W/"cb25-ZYwBHYqmEIx3l6cBBZRJvm6TS/E"',
     'content-encoding': 'gzip',
     date: 'Mon, 23 Sep 2019 23:38:24 GMT',
     connection: 'keep-alive' },
  isBase64Encoded: false }
END RequestId: 06cc4e3c-f533-18f2-e905-8795f9d88764
REPORT RequestId: 06cc4e3c-f533-18f2-e905-8795f9d88764	Duration: 22519.33 ms	Billed Duration: 22600 ms	Memory Size: 128 MB	Max Memory Used: 98 MB`

**Comment by t3dodson** [comment]
@sreekarsai08 How big? express has a limit on json size. If you are using `body-parser` add an option to increase the allowed payload size.
