### ISSUE TITLE
express server returns (non-decoded) base64 string for specific file

### ISSUE THREAD

**Issue by NqCompiler** [vendia/serverless-express#249]
Hey,
I am using aws-serverless-express for a reactjs web application, which lazy loads javascript files. I have configured the binaryMimeTypes to use gzip compression. Everything works great except for one specific file. When I lazyload this file my express server returns a not-decoded base64 string (which is the correct string - but non-decoded). This file has the exact same properties like any other lazyloaded javascript file. The only difference, I noticed so far, is the filesize (gzipped less than 1kb). 
Does it somehow ignore very small files when decoding base64 string?

My temporary solution right now is including this file in my main bundle. 
Thanks in advance!

**Comment by denissabramovs** [comment]
bump, same here...
I fear that this is not implemented, isn't it?

**Comment by brettstack** [comment]
If you're using Express compress middleware, this has a minimum threshold of 1kb and therefore won't be gzipped. Check out https://github.com/vendia/serverless-express/issues/99 for more info.
