### ISSUE TITLE
Always I use the example of aws-api AWS server say nodejs 8

### ISSUE THREAD

**Issue by killercuts** [vendia/serverless-express#263]
Always I use the example of aws-api AWS server say nodejs 8

How to use the lastest nodejs, where do I need to modify ?

**Comment by yuyokk** [comment]
@killercuts  Here https://github.com/awslabs/aws-serverless-express/blob/086714cb350c435b982eb58343fa58e028a4d746/examples/basic-starter/cloudformation.yaml#L60
change to `nodejs10.x`

**Comment by brett-vendia** [comment]
Example fixed in v4
