### ISSUE TITLE
Performance Issues and Questionable Architecture

### ISSUE THREAD

**Issue by avin-kavish** [vendia/serverless-express#271]
So I switched from pure lambda to this when the complexity of my application grew and I could no longer have a function per use case. Being able to use express for application logic was great but I noticed a significant performance drop. 50~200ms in some cases. Then I had a read through the code.

The implementation seems like a naive first attempt at making lambda work for express. "let's just launch a http server on a socket and forward lambda-proxy events to that socket" I would probably go that way too if I didn't understand express better. What express is is not a server. It's a middleware framework for a request, response pipeline. Hosting express on top of a http server is a choice. But in an environment such as lambda where the request is already processed into an application compatible format, i.e the lambda-proxy event object, there is no need for us to descend down to a socket and sent it back up through a server. All we need to do is to translate the request into an express compatible format and pass it through the already orchestrated middleware pipeline. Once the pipeline ends with a response, we just need to turn the response into a lambda compatible format. Which is what Doug has done with his library, [serverless-http](https://github.com/dougmoscrop/serverless-http). So I think in the spirit of open source, you need to either deprecate/archive this library and link to the other or rewrite this library to be much more efficient.

**Comment by Jokerobo** [comment]
I concur with the performance issue. Had to move to [serverless-http](serverless-http), which is so much faster.

**Comment by ffxsam** [comment]
I came here to ask about this too. Why is a socket-based server being created for a serverless process?

**Comment by nishant-dani** [comment]
I agree that the socket library is a huge overkill for the job of translating back and forth between lambda req response format to http.  It just needs format translation and to go the route of the overhead of an additional network listen + connect would be unnecessarily brute force.  It probably works without tears but the perf implications are non trivial.

**Comment by brettstack** [comment]
The reason we went with this approach years ago was that we didn't understand the edge cases we may encounter. Setting up the local socket was the path of least resistance.
