### ISSUE TITLE
Catch S3 triggers

### ISSUE THREAD

**Issue by zeeshan-maavan** [vendia/serverless-express#280]
is there any way I can get s3 event in any route?

**Comment by wrbejar** [comment]
teste

**Comment by brettstack** [comment]
We'll be releasing v4 in January. You can check out the branch now. With that you can write a custom event source mapper or even submit a PR to add it to the library for everyone.

**Comment by brettstack** [comment]
Check out this example in v4 https://github.com/vendia/serverless-express/blob/mainline/examples/custom-mapper-dynamodb/src/lambda.js
