### ISSUE TITLE
Override getEventBody set Buffer encode from 'utf8' to 'binary'

### ISSUE THREAD

**Issue by abinhho** [vendia/serverless-express#286]
Hello,
```
function getEventBody (event) {
  return Buffer.from(event.body, event.isBase64Encoded ? 'base64' : 'utf8')
}
```
I am using serverless and NestJS, I trying to upload image but the `body` has been converted to `Buffer` then send to `Node Server` using function  `getEventBody` above. 

But if `utf8`, I could not parse image from body, I need switch to something like this:
```
function getEventBody (event) {
  return Buffer.from(event.body, event.isBase64Encoded ? 'base64' : 'binary') // <--- Here
}
```

So are there any ways to custom this function?

This is the code in `nodejs` server

```
req.on("data", function(chunk) {
  data.push(chunk);
})
.on("end", function() {
  body = Buffer.concat(data).toString();
  var bb = new busboy({ headers: { 'content-type': contentType } });

  bb.on('file', function (fieldname, file, filename, encoding, mimetype) {
    const mimeType = mimetype;
    const ext = filename.split('.')[1];
    let chunks;
    file.on('data', function (data) {
      chunks = data;
    }).on('end', function () {
      let base64Image = new Buffer(chunks.toString(), 'binary').toString('base64');
      const fileData = new Buffer(base64Image, 'base64');
    });
  })

  bb.end(body);
```

Please help!

**Comment by brettstack** [comment]
I believe the correct way to do this with API Gateway is to add the mime type to the binaryMediaTypes in API Gateway so that they're base64 encoded when the request is made to Lambda https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html.
