### ISSUE TITLE
How to get the client real ip (x-forwarded-for) and the client requested hostname?

### ISSUE THREAD

**Issue by neko1101** [vendia/serverless-express#290]
Hey guys,

I'm implementing some analytics where i need to use the client real ip (not the api-gateway/cloudfront ip) to detect ip geolocation.

Secondly, I need the requested hostname because i'm implementing custom route for custom domain.

Anyone could help me to understand how can i achieve this?

Thanks!

**Comment by brettstack** [comment]
You can use `getCurrentInvoke` to get any details that the Lambda was originally invoked with https://github.com/vendia/serverless-express/blob/mainline/examples/basic-starter-api-gateway-v1/src/app.js#L6-L30. Is that information available there? If not, there's nothing we can do.
