### ISSUE TITLE
Any impact due to middleware in express app

### ISSUE THREAD

**Issue by vishwasrao** [vendia/serverless-express#294]
We are using same code base for express based application as well as lambda.
As per configuration we have used 
```
const awsServerlessExpressMiddleware = require('aws-serverless-express/middleware');
app.use(awsServerlessExpressMiddleware.eventContext());
```
in our app.js file.

Currently we do not see any issues into our standalone application.
Both (Lambda deployment, express based application) are working fine.

Do we need to consider something while running application in standalone mode (without lambda) ?

**Comment by wattry** [comment]
It should not cause any issues sincethis method converts the x-apigateway-event or x-apigateway-context header to the event and context objects. However, you will see this error in your logs: 'Missing x-apigateway-event or x-apigateway-context header(s)'.
