### ISSUE TITLE
Docs don't describe how to define binary mimetypes - necessary for returning binary responses

### ISSUE THREAD

**Issue by Craigfis** [vendia/serverless-express#307]
Took me a while to figure out why returning a binary file from my API wasn't working. Eventually pulled down the source code for aws-serverless-express and found it wasn't setting the isBase64Encoded flag and that createServer method has an undocumented parameter that takes an array of mimetypes that should be treated as binary.

**Comment by brettstack** [comment]
In v4 this is detected automatically
