### ISSUE TITLE
Future of this project 

### ISSUE THREAD

**Issue by Muthuveerappanv** [vendia/serverless-express#314]
@sapessi - am running express lambda in production using this library. Considering that this project has not been update in a while & with issues open and no one looking into them. I would like to know if this library is going to be update by awslabs and maintained ?

**Comment by sapessi** [comment]
Hi @Muthuveerappanv - we'll have an update for you over the next couple of weeks.

**Comment by wattry** [comment]
Agreed, it's hard enough trying to convince teams to move to serverless.

**Comment by er-dev** [comment]
Would love to see that promised update! Was having great progress porting an Express app over to Lambda, then I hit #134 and its game over. AWS seemingly dropping support for this repo gives me cold feet.

**Comment by sapessi** [comment]
Apologies for the delay all. We have just updated the main README of the project with our plan for the future - spoiler alert, @brettstack is back! 

Message below:

---
# AWS Serverless Express is moving

On 11/30, the AWS Serverless Express library is moving to [Vendia](https://github.com/vendia) and will be rebranded to `serverless-express`. Similarly, the [`aws-serverless-express` NPM package](https://www.npmjs.com/package/aws-serverless-express) will be deprecated in favor of a new `serverless-express` package. 

[Brett](https://github.com/brettstack), the original creator of the Serverless Express library, will continue maintaining the repository and give it the attention and care it deserves. At the same time, we will be looking for additional contributors to participate in the development and stewardship of the Serverless Express library. AWS and the [SAM team](https://github.com/aws/aws-sam-cli) will remain involved in an administrative role alongside Vendia, Brett, and the new maintainers that will join the project.

We believe this is the best course of action to ensure that customers using this library get the best possible support in the future. To learn more about this move or become a maintainer of the new Serverless Express library, reach out to us through a GitHub issue on this repository. 

Best,
  The AWS Serverless team, Brett & the Vendia team

**Comment by wattry** [comment]
Thanks for the update, there is already a [serverless-express](https://www.npmjs.com/package/serverless-express) package this may cause some confusion.

**Comment by sapessi** [comment]
Sigh, thanks for letting us know. We'll figure out a name and update the message.

**Comment by eahefnawy** [comment]
The `serverless-http` package is a pretty good alternative with less footprint:

https://github.com/dougmoscrop/serverless-http
