### ISSUE TITLE
"Error: Cannot find module '@vendia/serverless-express'

### ISSUE THREAD

**Issue by selected-pixel-jameson** [vendia/serverless-express#324]
I have not changed anything with my build process, but for some reason I'm now getting this error when deploying to my development and production environments. 

Seems to work fine on my local. 

{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@vendia/serverless-express'\nRequire stack:\n- /var/task/lambda.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@vendia/serverless-express'",
        "Require stack:",
        "- /var/task/lambda.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1015:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)",
        "    at Module.load (internal/modules/cjs/loader.js:879:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}

**Comment by brettstack** [comment]
Sorry you're hitting this. Could you show your `lambda.js` and the serverless-express entry in `package.json`?

**Comment by kittholland** [comment]
Not the original issue author, but I am experiencing the exact same issue:

Package.json:
`"aws-serverless-express": "^3.2.0"
`
Lambda.js

```
// generated by @ng-toolkit/serverless
const awsServerlessExpress = require('aws-serverless-express');
const server = require('./dist/server');
const awsServerlessExpressMiddleware = require('aws-serverless-express/middleware');

const binaryMimeTypes = [
  'application/javascript',
  'application/json',
  'application/octet-stream',
  'application/xml',
  'image/jpeg',
  'image/png',
  'image/gif',
  'text/comma-separated-values',
  'text/css',
  'text/html',
  'text/javascript',
  'text/plain',
  'text/text',
  'text/xml',
  'image/x-icon',
  'image/svg+xml',
  'application/x-font-ttf',
  'font/ttf',
  'font/woff',
  'font/woff2',
  'application/font-woff',
  'application/font-woff2',
  'application/x-font-woff',
  'application/x-font-woff2'
];

server.app.use(awsServerlessExpressMiddleware.eventContext());

const serverProxy = awsServerlessExpress.createServer(server.app, null, binaryMimeTypes);
module.exports.universal = (event, context) => awsServerlessExpress.proxy(serverProxy, event, context);


```

**Comment by kittholland** [comment]
I npm installed @vendia/serverless-express, npm removed aws-serverless-express and updated the two requires in the lambda.js but I'm still receiving this issue.

**Comment by brett-vendia** [comment]
@selected-pixel-jameson are you also using @ng-toolkit/serverless? I wonder if it's something different there. You can get the example https://github.com/vendia/serverless-express/tree/master/examples/basic-starter up and running and maybe compare what's different?

**Comment by kittholland** [comment]
So we figured it out, it's an interaction with the serverless deploy, it automatically applies an ignore to certain paths in node-modules for the aws-serverless-express in the serverless.yml. Once we updated those to exclude the new name/path it worked.

Snip from serverless.yml:
```

package:
  exclude:
   - src/**
   - node_modules/**
   - firebug-lite/**
   - e2e/**
   - coverage/**
   - '!node_modules/@vendia/**'
   - '!node_modules/aws-/**'
   - '!node_modules/binary-case/**'
   - '!node_modules/type-is/**'
   - '!node_modules/media-typer/**'
   - '!node_modules/mime-types/**'
   - '!node_modules/mime-db/**'

```

**Comment by brett-vendia** [comment]
Glad you fixed it. Closing
